### PR TITLE
Restructured complete Repo: DO NOT MERGE RIGHT NOW

### PR DESCRIPTION
**Pull request by varunu28**
@AnupKumarPanwar @dynamitechetan 

I have restructured the complete repo and added tests for the search algorithms. Please review it once and do let me know if it looks good. Suggest what changes should be done.

Note for everyone else: This is a test PR. Do not approve or close it. I will close it once the purpose is fulfilled. Thanks

### CODE REVIEW

**Comment by dynamitechetan** [comment]
The structure looks fine. Some algorithms are still missing from the src folder. Please add them too ;D.

**Comment by varunu28** [comment]
@dynamitechetan Yeah I just kept the search algorithms for now. I would add the sorting algorithms along with the test cases and only move the code to main repo

**Comment by andreicioban** [comment]
@varunu28 , please remove(ignore) `target/` folder to make this PR lighter and easier to review.

**Comment by varunu28** [comment]
@andreicioban Please let me know if its ok now. I have added the target files to be ignored.

**Comment by andreicioban** [comment]
@varunu28 the files seem to still be in the PR. You need to also remove them from remote:

```shell
git rm -r --cached target/
git commit -m 'Remove the now ignored directory target'
git push origin branch
```

**Comment by varunu28** [comment]
@dynamitechetan @AnupKumarPanwar @andreicioban 
I have added the sort algorithms and their test specs. I have also removed the target files

I did not add the bogo sort as it seemed broken. Do review the commits once and if everything looks fine we can move forward with merge to change the repository structure. 
Let me know if any changes are required. 

Thanks

**Comment by varunu28** [comment]
@dynamitechetan @andreicioban Kindly review this PR so that we can merge it and move forward with adding more algorithms in the same structure

**Comment by varunu28** [comment]
@andreicioban  Done with removing project target

I will keep a note of the removal of project/target and target files from the PR in README for contributors. It would be kind of a checklist for a PR

**Comment by varunu28** [comment]
@dynamitechetan @andreicioban If everything looks good, I can merge it with the master repo

**Comment by andreicioban** [comment]
@varunu28 is ok from my side 👍

**Comment by varunu28** [comment]
@andreicioban Lets go with the merge then. I am merging it with the master

**Pull request merged**
