### PR TITLE
Add missing docs and upgrade dependencies

### LINKED ISSUE #2: Add more algorithms
Please add more algorithms to this repo. 

See the structure and README of this repo for reference
https://github.com/TheAlgorithms/Python

### LINKED ISSUE #9: Change readme.md
The readme.md file of this repo appears to be specific for sorting algorithms only. The needs to be updated with suitable description. Comment for the suggestions.

And for algorithms description send PRs on [Algorithms-Explained](https://github.com/TheAlgorithms/Algorithms-Explainations) repo.

### LINKED ISSUE #41: A series of compilation/test errors in the math algorithms
## Error 1

The function `abs` seems to be not in the global namespace.

```text
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\main\scala\Mathematics\AbsMax.scala:11:42: not found: value abs
[error]         def absMax(elements : List[Int]): Int = abs(elements.maxBy(x => abs(x)))
[error]                                                 ^
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\main\scala\Mathematics\AbsMax.scala:11:66: not found: value abs
[error]         def absMax(elements : List[Int]): Int = abs(elements.maxBy(x => abs(x)))
[error]                                                                         ^
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\main\scala\Mathematics\AbsMax.scala:11:60: diverging implicit expansion for type Ordering[B]
[error] starting with method Tuple9 in object Ordering
[error]         def absMax(elements : List[Int]): Int = abs(elements.maxBy(x => abs(x)))
[error]                                                                   ^
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\main\scala\Mathematics\AbsMin.scala:11:42: not found: value abs
[error]         def absMin(elements : List[Int]): Int = abs(elements.minBy(x => abs(x)))
[error]                                                 ^
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\main\scala\Mathematics\AbsMin.scala:11:66: not found: value abs
[error]         def absMin(elements : List[Int]): Int = abs(elements.minBy(x => abs(x)))
[error]                                                                         ^
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\main\scala\Mathematics\AbsMin.scala:11:60: diverging implicit expansion for type Ordering[B]
[error] starting with method Tuple9 in object Ordering
[error]         def absMin(elements : List[Int]): Int = abs(elements.minBy(x => abs(x)))
[error]                                                                   ^
[error] 6 errors found
[error] (compile:compileIncremental) Compilation failed
```

This can be fixed by adding `import scala.math._`

## Error 2

A right parenthesis is missing in a test case.

```text
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\test\scala\Array\MaximumAbsoluteDifferenceSpec.scala:9:3: ')' expected but '}' found.
[error]   }
[error]   ^
[error] one error found
[error] (test:compileIncremental) Compilation failed
[error] Total time: 4 s, completed 2020-1-12 22:23:58
```

This can be fixed by changing `assert(MaximumAbsoluteDifferenceSpec.maxAbsDiff(Array(1, 3, -1) === 5)` to `assert(MaximumAbsoluteDifferenceSpec.maxAbsDiff(Array(1, 3, -1)) === 5)` in https://github.com/TheAlgorithms/Scala/blob/42a0aefd5d19a11560f69b52aa2b9d36e359a504/src/test/scala/Array/MaximumAbsoluteDifferenceSpec.scala#L8.

## Error 3

(folding other similar errors)

```text
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\test\scala\Sort\SelectionSortSpec.scala:9:49: package Array is not a value
[error]     assert(SelectionSort.selectionSort(arr) === Array(0,1,2,3,7,9))
[error]                                                 ^
[error] 32 errors found
[error] (test:compileIncremental) Compilation failed
[error] Total time: 1 s, completed 2020-1-12 22:29:51
```

The problem, `package Array is not a value`, seems to happen because the package name conflicts with the `Array` scala type, therefore can be fixed with changing `package Array` to `package ArrayTest`.

## Error 4

```text
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\test\scala\Array\MaximumAbsoluteDifferenceSpec.scala:8:12: not found: value MaximumAbsoluteDifferenceSpec
[error]     assert(MaximumAbsoluteDifferenceSpec.maxAbsDiff(Array(1, 3, -1)) === 5)
[error]            ^
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\test\scala\Array\MaximumAbsoluteDifferenceSpec.scala:12:12: not found: value MaximumAbsoluteDifferenceSpec
[error]     assert(MaximumAbsoluteDifferenceSpec.maxAbsDiff(Array(4, 3, 0, 9, -1, 6, -5)) === 17)
```

I do not know where does the `maxAbsDiff` comes from. There is not even a method definition. All I can do is to delete that file.

## Error 5

```text
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\test\scala\Mathematics\AbsMaxSpec.scala:8:33: 6 more arguments than can be applied to method absMax: (elements: List[Int])Int
[error]     assert(AbsMax.absMax(-1000, -1, 999, 72, 65, -56, -767) === 1000)
[error]                                 ^
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\test\scala\Mathematics\AbsMaxSpec.scala:12:31: 3 more arguments than can be applied to method absMax: (elements: List[Int])Int
[error]     assert(AbsMax.absMax(121, 221, 3, 4112) === 4112)
[error]                               ^
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\test\scala\Mathematics\AbsMinSpec.scala:8:32: 6 more arguments than can be applied to method absMin: (elements: List[Int])Int
[error]     assert(AbsMin.absMin(1000, -1, 999, 72, 65, -56, -767) === 1)
[error]                                ^
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\test\scala\Mathematics\AbsMinSpec.scala:12:31: 3 more arguments than can be applied to method absMin: (elements: List[Int])Int
[error]     assert(AbsMin.absMin(121, 221, 3, 4112) === 3)
[error]                               ^
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\test\scala\Mathematics\FindMaxSpec.scala:8:35: 6 more arguments than can be applied to method findMax: (elements: List[Int])Int
[error]     assert(FindMax.findMax(-1000, -1, 999, 72, 65, -56, -767) === 999)
[error]                                   ^
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\test\scala\Mathematics\FindMaxSpec.scala:12:33: 3 more arguments than can be applied to method findMax: (elements: List[Int])Int
[error]     assert(FindMax.findMax(121, 221, 3, 4112) === 4112)
[error]                                 ^
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\test\scala\Mathematics\FindMinSpec.scala:8:35: 6 more arguments than can be applied to method findMin: (elements: List[Int])Int
[error]     assert(FindMin.findMin(-1000, -1, 999, 72, 65, -56, -767) === -1000)
[error]                                   ^
[error] C:\Personal\gitkrakenRepo\Scala-Algorithms\src\test\scala\Mathematics\FindMinSpec.scala:12:33: 3 more arguments than can be applied to method findMin: (elements: List[Int])Int
[error]     assert(FindMin.findMin(121, 221, 3, 4112) === 3)
```

These failures suggest type mismatch from a List to a series of Numbers, which can be fixed via changing, for example, `assert(AbsMax.absMax(-1000, -1, 999, 72, 65, -56, -767) === 1000)` to `assert(AbsMax.absMax(List(-1000, -1, 999, 72, 65, -56, -767)) === 1000)`.

## Error 6

```text
[info] Mathematics.AbsMaxSpec *** ABORTED ***
[info]   Duplicate test name: should output the correct Integer as a result from the list of elements (AbsMaxSpec.scala:11)
[info] AbsMinSpec:
[info] FindMaxSpec:
[info] FindMinSpec:
[info] AbsSpec:
[info] Run completed in 896 milliseconds.
[info] Total number of tests run: 30
[info] Suites: completed 17, aborted 6
[info] Tests: succeeded 30, failed 0, canceled 0, ignored 0, pending 0
[info] *** 6 SUITES ABORTED ***
[error] Error during tests:
[error]         Mathematics.AbsMaxSpec
[error]         Mathematics.AbsMinSpec
[error]         Mathematics.FindMinSpec
[error]         Mathematics.GreaterCommonDivisorSpec
[error]         Mathematics.FindMaxSpec
[error]         Mathematics.AbsSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 4 s, completed 2020-1-12 22:42:05
```

Lots of test suites failed. Because their description is duplicated (Duplicate test name), I cannot even locate the problem.

---

Am I missing something in the environment setup? Or is the project just unmaintained and the CI is not running? The second error, missing right parenthesis, does not look like anything that could possibly originate from my flawed environment setup but rather a human error, which should be detected by the CI.

### PR DESCRIPTION
**Pull request by sentenza**
Close #2 

Close #9

Close #41

# Tasks

- [x] Update .gitignore 
- [x] Add Scalafmt
- [x] Update travis conf
- [x] Add CONTRIBUTING
- [x] Update DIRECTORY listing all the missing algorithms taken from Java project #2 
- [x] Fix README #9 
- [x] Updgrade sbt to v1.5.5 (latest)
- [x] Upgrade scala to v2.13.6
- [x] Fix several compiling error (after adding Xlint via tpolect plugin)

### CODE REVIEW

**Comment by sentenza** [comment]
@Panquesito7 follow up of our discussion on #9

**Comment by cclauss** [comment]
Also #59 

Scala is not supported by LGTM https://lgtm.com/help/lgtm/about-lgtm#languages

**Comment by Panquesito7** [comment]
> @Panquesito7 This [GH workflow](https://github.com/sentenza/Scala/blob/master/.github/workflows/directory_workflow.yml) should be changed to be compatible with the new Directory scheme used by both Python and Java projects.

Feel free to make a PR for that, and we'll review it. 🙂

**Comment by sentenza** [comment]
> 
> 
> > @Panquesito7 This [GH workflow](https://github.com/sentenza/Scala/blob/master/.github/workflows/directory_workflow.yml) should be changed to be compatible with the new Directory scheme used by both Python and Java projects.
> 
> Feel free to make a PR for that, and we'll review it. 🙂

No idea how to fix that to be honest. I've never seen/used that plugin before. I don't even know where the configuration has been applied to enable it. 

@Panquesito7 I applied your suggested change. ;)

**Comment by sentenza** [comment]
> 
> 
> How about add `scalafmtOnCompile := true` in `build.sbt` ?

@counter2015 I think it would make sense adding a new GitHub workflow for scalafmt on top of that. I'm going to add your suggested change. 👌

**Comment by counter2015** [comment]
> I guess that all the review comments were addressed and this PR could be merged in.
> 
> The LGTM thingy is not related to this PR.
> 
> @cclauss @Panquesito7 @counter2015 WDYT? 👂

LGTM, thanks your work!

**Comment by sentenza** [comment]
@cclauss @Panquesito7 @counter2015 Can we merge this PR in? I would really love to keep working on other algorithms on top of the changes introduced here. I think that everyone here approved it already.

**Comment by counter2015** [comment]
merged

**Pull request merged**
